M48
; DRILL file {KiCad 7.0.7} date Sun Dec 10 12:52:58 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-10T12:52:58-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1063
%
G90
G05
T1
X6.0433Y-3.3012
X6.0433Y-3.5965
T2
X4.0748Y-2.8937
X4.0748Y-3.7992
X6.3583Y-2.8937
X6.3583Y-3.7992
T0
M30
